# Generated by Django 5.1.3 on 2024-11-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsemester',
            name='code',
            field=models.CharField(max_length=1),
        ),
    ]
