# Generated by Django 5.1.3 on 2024-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_utils', '0003_alter_academicfaculty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='eke_name',
            field=models.CharField(max_length=10),
        ),
    ]
