# Generated by Django 5.1.3 on 2024-11-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_utils', '0004_alter_academicprogram_eke_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicsemester',
            unique_together={('name', 'year')},
        ),
    ]
