# Generated by Django 5.1.3 on 2024-11-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER')], max_length=10),
        ),
    ]
